import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Hydrate from "./components/Hydrate";
import Navbar from "./components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations";
import Stripe from "stripe";

// Carregar fontes personalizadas com next/font
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadados da aplicação
export const metadata: Metadata = {
  title: "Techcore",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={ptBR}>
      <html lang="pt-BR">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
          suppressHydrationWarning={true} // Suprime os warnings de hidratação
        >
          <Hydrate>
            <Navbar />
            <main className="h-screen p-16 text-purple-400 text-md">
              {children}
            </main>
            </Hydrate>
        </body>
      </html>
    </ClerkProvider>
  );
}
